"""
Initial catalog seed data for the Acai da Vila demo store.

The seed only runs when the categories collection is empty. Existing catalog
data is never removed automatically.
"""

ACAI_CATEGORY_NAME = "A\u00e7a\u00ed no Copo"


def acai_option_groups(product_slug):
    return [
        {
            "id": f"{product_slug}-fruta",
            "name": "Escolha uma fruta",
            "description": "Selecione uma fruta para acompanhar seu a\u00e7a\u00ed.",
            "highlight_text": "",
            "required": True,
            "min_selections": 1,
            "max_selections": 1,
            "selection_type": "single",
            "order": 0,
            "active": True,
            "options": [
                {
                    "id": f"{product_slug}-fruta-banana",
                    "name": "Banana",
                    "description": "",
                    "additional_price": 0,
                    "max_quantity": 1,
                    "order": 0,
                    "active": True,
                },
                {
                    "id": f"{product_slug}-fruta-morango",
                    "name": "Morango",
                    "description": "",
                    "additional_price": 0,
                    "max_quantity": 1,
                    "order": 1,
                    "active": True,
                    "recommended": True,
                },
                {
                    "id": f"{product_slug}-fruta-manga",
                    "name": "Manga",
                    "description": "",
                    "additional_price": 0,
                    "max_quantity": 1,
                    "order": 2,
                    "active": True,
                },
                {
                    "id": f"{product_slug}-fruta-abacaxi",
                    "name": "Abacaxi",
                    "description": "",
                    "additional_price": 0,
                    "max_quantity": 1,
                    "order": 3,
                    "active": True,
                },
            ],
        },
        {
            "id": f"{product_slug}-acompanhamentos",
            "name": "Escolha at\u00e9 tr\u00eas acompanhamentos",
            "description": "Monte do seu jeito com at\u00e9 tr\u00eas acompanhamentos.",
            "highlight_text": "Ovomaltine deixa o copo mais crocante.",
            "required": False,
            "min_selections": 0,
            "max_selections": 3,
            "selection_type": "multiple",
            "order": 1,
            "active": True,
            "options": [
                {
                    "id": f"{product_slug}-acomp-granola",
                    "name": "Granola",
                    "description": "",
                    "additional_price": 0,
                    "max_quantity": 1,
                    "order": 0,
                    "active": True,
                    "popular": True,
                },
                {
                    "id": f"{product_slug}-acomp-leite-condensado",
                    "name": "Leite condensado",
                    "description": "",
                    "additional_price": 0,
                    "max_quantity": 1,
                    "order": 1,
                    "active": True,
                },
                {
                    "id": f"{product_slug}-acomp-leite-em-po",
                    "name": "Leite em p\u00f3",
                    "description": "",
                    "additional_price": 0,
                    "max_quantity": 1,
                    "order": 2,
                    "active": True,
                },
                {
                    "id": f"{product_slug}-acomp-pacoca",
                    "name": "Pa\u00e7oca",
                    "description": "",
                    "additional_price": 0,
                    "max_quantity": 1,
                    "order": 3,
                    "active": True,
                },
                {
                    "id": f"{product_slug}-acomp-ovomaltine",
                    "name": "Ovomaltine",
                    "description": "",
                    "additional_price": 2.00,
                    "max_quantity": 1,
                    "order": 4,
                    "active": True,
                    "recommended": True,
                },
            ],
        },
        {
            "id": f"{product_slug}-cobertura",
            "name": "Escolha uma cobertura",
            "description": "Finalize com uma cobertura.",
            "highlight_text": "",
            "required": True,
            "min_selections": 1,
            "max_selections": 1,
            "selection_type": "single",
            "order": 2,
            "active": True,
            "options": [
                {
                    "id": f"{product_slug}-cobertura-sem",
                    "name": "Sem cobertura",
                    "description": "",
                    "additional_price": 0,
                    "max_quantity": 1,
                    "order": 0,
                    "active": True,
                },
                {
                    "id": f"{product_slug}-cobertura-chocolate",
                    "name": "Chocolate",
                    "description": "",
                    "additional_price": 0,
                    "max_quantity": 1,
                    "order": 1,
                    "active": True,
                    "popular": True,
                },
                {
                    "id": f"{product_slug}-cobertura-morango",
                    "name": "Morango",
                    "description": "",
                    "additional_price": 0,
                    "max_quantity": 1,
                    "order": 2,
                    "active": True,
                },
                {
                    "id": f"{product_slug}-cobertura-caramelo",
                    "name": "Caramelo",
                    "description": "",
                    "additional_price": 0,
                    "max_quantity": 1,
                    "order": 3,
                    "active": True,
                },
            ],
        },
        {
            "id": f"{product_slug}-talher",
            "name": "Precisa de talher?",
            "description": "Informe se deseja receber talher descart\u00e1vel.",
            "highlight_text": "",
            "required": True,
            "min_selections": 1,
            "max_selections": 1,
            "selection_type": "single",
            "order": 3,
            "active": True,
            "options": [
                {
                    "id": f"{product_slug}-talher-sim",
                    "name": "Sim",
                    "description": "",
                    "additional_price": 0,
                    "max_quantity": 1,
                    "order": 0,
                    "active": True,
                },
                {
                    "id": f"{product_slug}-talher-nao",
                    "name": "N\u00e3o",
                    "description": "",
                    "additional_price": 0,
                    "max_quantity": 1,
                    "order": 1,
                    "active": True,
                },
            ],
        },
    ]


SEED_CATEGORIES = [
    {
        "name": ACAI_CATEGORY_NAME,
        "icon": "cup-soda",
        "description": "Copos de a\u00e7a\u00ed para montar com frutas, acompanhamentos e coberturas.",
        "display_order": 0,
    },
]

SEED_PRODUCTS = [
    {
        "name": "A\u00e7a\u00ed 300 ml",
        "description": "Copo individual de a\u00e7a\u00ed cremoso para personalizar.",
        "category_name": ACAI_CATEGORY_NAME,
        "price": 18.00,
        "promo_active": False,
        "promo_price": None,
        "image_url": "",
        "display_order": 0,
        "option_groups": acai_option_groups("acai-300"),
    },
    {
        "name": "A\u00e7a\u00ed 400 ml",
        "description": "Tamanho medio para combinar frutas, acompanhamentos e cobertura.",
        "category_name": ACAI_CATEGORY_NAME,
        "price": 22.00,
        "promo_active": False,
        "promo_price": None,
        "image_url": "",
        "display_order": 1,
        "option_groups": acai_option_groups("acai-400"),
    },
    {
        "name": "A\u00e7a\u00ed 500 ml",
        "description": "Copo generoso de a\u00e7a\u00ed para uma montagem completa.",
        "category_name": ACAI_CATEGORY_NAME,
        "price": 27.00,
        "promo_active": False,
        "promo_price": None,
        "image_url": "",
        "display_order": 2,
        "option_groups": acai_option_groups("acai-500"),
    },
    {
        "name": "A\u00e7a\u00ed 700 ml",
        "description": "Copo grande para quem quer caprichar nos adicionais.",
        "category_name": ACAI_CATEGORY_NAME,
        "price": 34.00,
        "promo_active": False,
        "promo_price": None,
        "image_url": "",
        "display_order": 3,
        "option_groups": acai_option_groups("acai-700"),
    },
]
