export const STORE_CONFIG_FALLBACK = {
  name: "Adega Drinks",
  primary_color: "#3B2416",
  secondary_color: "#D49A2A",
  whatsapp_number: "",
  banner_url: "https://images.unsplash.com/photo-1470337458703-46ad1756a187?auto=format&fit=crop&w=2000&q=85",
  store_banner_url: "",
  logo_url: "",
  store_logo_url: "",
  tagline: "os melhor copão de cidade",
  banner_title: "Adega Drinks",
  banner_subtitle: "os melhor copão de cidade",
  banner_button_text: "",
  banner_button_link: "",
  banner_enabled: true,
  search_placeholder: "Buscar produtos...",
  address: "",
  pix_key: "",
  pix_key_type: "",
  delivery_note: "Trabalhamos com entregas e retiradas",
  checkout_note: "Seu pedido será aberto no WhatsApp da loja já preenchido.",
  public_domain: "",
  age_gate_enabled: false,
  age_gate_min_age: 18,
  age_gate_title: "Confirmação de idade",
  age_gate_message: "Confirme que você possui a idade mínima exigida para acessar esta loja.",
  business_hours_enabled: false,
  business_hours_timezone: "America/Sao_Paulo",
  business_hours: {},
  free_shipping_enabled: false,
  free_shipping_minimum: 0,
};
