export const STORE_CONFIG_FALLBACK = {
  name: "Loja White Label",
  primary_color: "#722F37",
  secondary_color: "#C89F53",
  whatsapp_number: "",
  banner_url: "",
  store_banner_url: "",
  logo_url: "",
  store_logo_url: "",
  tagline: "",
  banner_title: "",
  banner_subtitle: "",
  banner_button_text: "",
  banner_button_link: "",
  banner_enabled: true,
  search_placeholder: "Buscar produtos...",
  address: "",
  pix_key: "",
  pix_key_type: "",
  delivery_note: "",
  checkout_note: "Seu pedido será aberto no WhatsApp da loja já preenchido.",
  public_domain: "",
  age_gate_enabled: false,
  age_gate_min_age: 18,
  age_gate_title: "Confirmação de idade",
  age_gate_message: "Confirme que você possui a idade mínima exigida para acessar esta loja.",
  business_hours_enabled: false,
  business_hours_timezone: "America/Sao_Paulo",
  business_hours: {},
  free_shipping_enabled: false,
  free_shipping_minimum: 0,
};
